### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by scooby3** [sl5net/global-IntelliSense-everywhere#5]
Hi,

I like this project and would like to use it alot.

I have a problem with language.

I am Swedish and the Swedish special characters does not show correctly.

This may be unrelated but I get a warning message "language.xml is not loaded, recover?"
I am not sure if it is a configuration?

Other ahk scripts can handle these characters perfectly

Any idea how to fix this?

**Comment by sl5net** [comment]
The error caused by a missing XML file for Notepad++ portable (language.xml is used bei Notepad++).
Now the default editor of Windows is temporarily used.
The mistake should be gone I'll test it afterwards.

You could configere this yourself here:
Source\inc_ahk\openInEditor_actionList.inc.ahk

Does it work also for you now?
If not, please proof that you really using utf-8
